### ISSUE TITLE
Hardware connections

### ISSUE THREAD

**Issue by AnjanaNiranjan** [experiencor/self-driving-toy-car#1]
Hello! Thank you for the great tutorial! Can you please explain the hardware connections? What car have you used? You've mentioned only pin 17 for data collection and pin 18 for autonomous driving. What are the othe connections?

**Comment by experiencor** [comment]
@AnjanaNiranjan 

1. There are 3 connections between Pi and the car: 2 PWMs from Pi to control the car and 1 line to connect the '-' heads from 2 power sources (1 powers motor, 1 powers Pi).
2. It's thís one: Veterra Halix 1:10. This one does not matter but my advice is to buy slower cars like a rock crawler. My car is too fast.
3. I think not possible as the image conditions are different.
